# Repository settings for GitHub
repository:
  name: bedrock-cross-partition-inferencing
  description: "🚀 Enable AWS GovCloud applications to access Commercial Bedrock models through a secure, compliant proxy"
  homepage: https://github.com/freshie/bedrock-cross-partition-inferencing
  topics:
    - aws
    - bedrock
    - govcloud
    - ai
    - serverless
    - cross-partition
    - lambda
    - api-gateway
    - machine-learning
    - artificial-intelligence
    - government
    - compliance
    - security
    - infrastructure-as-code
    - cloudformation
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true

# Labels for issues and PRs
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: security
    color: b60205
    description: Security-related issues
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: question
    color: d876e3
    description: Further information is requested
  - name: v1.0
    color: fbca04
    description: Version 1.0 - Over the Internet
  - name: v2.0
    color: fbca04
    description: Version 2.0 - VPN Connectivity
  - name: v3.0
    color: fbca04
    description: Version 3.0 - Direct Connect

# Branch protection rules
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      restrictions: null