#!/bin/bash

# Cross-Partition Bedrock Inference Configuration Example
# Copy this file to config.sh and update with your actual values
# Generated by: ./scripts/get-config.sh

# =============================================================================
# API Gateway Configuration (from CloudFormation)
# =============================================================================

# Your API Gateway base URL
export API_BASE_URL="https://YOUR_API_ID.execute-api.us-gov-west-1.amazonaws.com/v1"

# Specific endpoints
export BEDROCK_ENDPOINT="https://YOUR_API_ID.execute-api.us-gov-west-1.amazonaws.com/v1/bedrock/invoke-model"
export MODELS_ENDPOINT="https://YOUR_API_ID.execute-api.us-gov-west-1.amazonaws.com/v1/bedrock/models"

# =============================================================================
# AWS Configuration
# =============================================================================

# AWS Region where your infrastructure is deployed
export AWS_REGION="us-gov-west-1"

# AWS Profile used for deployment
export AWS_PROFILE="govcloud"

# CloudFormation stack name
export STACK_NAME="cross-partition-inference-mvp"

# =============================================================================
# Security Configuration
# =============================================================================

# Secrets Manager secret name for Bedrock credentials
export BEDROCK_SECRET_NAME="arn:aws-us-gov:secretsmanager:us-gov-west-1:YOUR_ACCOUNT_ID:secret:cross-partition-commercial-creds-XXXXXX"

# =============================================================================
# Testing Configuration
# =============================================================================

# Model ID to use for testing
export TEST_MODEL_ID="anthropic.claude-3-5-sonnet-20241022-v2:0"

# Maximum tokens for test requests
export TEST_MAX_TOKENS="1000"

# =============================================================================
# Usage Instructions
# =============================================================================
# 1. Copy this file: cp config/config.example.sh config/config.sh
# 2. Run: ./scripts/get-config.sh (to auto-populate from CloudFormation)
# 3. Or manually edit config/config.sh with your values
# 4. Source the config: source config/config.sh
